config/routes.rb
Rails.application.routes.draw do
	mount Sidekiq::Monitor::Engine => '/sidekiq'
  resources :email_templates
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/customers/send_single_mail', to: 'customers#send_single_mail'
  post '/customers/send_multi_mail', to: 'customers#send_multi_mail'
  post '/customers/send_all_mail', to: 'customers#send_all_mail'
  post '/customers/import', to: 'customers#import'

  post '/email_templates/choose_template', to: 'email_templates#choose_template'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
require 'csv'

class Customer < ApplicationRecord
	validates :email, uniqueness: true

	def self.import(file)
		@errors = []
	  CSV.foreach(file.path, headers: true) do |row|
	  	email = row.to_hash["email"]
	  	customer = Customer.new row.to_hash
	  	unless customer.save
	  		customer.errors.full_messages.each do |message|
	        @errors << "#{email}: #{message}"
	      end
	  	end
	  end
	  @errors
	end
end

app/models/email_template.rb
class EmailTemplate < ApplicationRecord
end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all.order(updated_at: :desc).page(params[:page]).per(50)
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customers_path, notice: 'Customer was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customers_path, notice: 'Customer was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_single_mail
    ids = []
    ids << params[:id]
    EmailWorker.perform_async(ids)
  end

  def send_multi_mail
    if params[:max].present?
      arr = Customer.offset(params[:min].to_i).limit(params[:max].to_i).pluck(:id)
    else
      arr = Customer.offset(params[:min].to_i).pluck(:id)
    end
    q = 8
    sl = (arr.size % q != 0) ? (arr.size / q + 1) : (arr.size / q)
    slice = arr.each_slice(sl).to_a
    slice.each do |ids|
      EmailWorker.perform_async(ids)
    end
  end

  def send_all_mail
    arr = Customer.all.pluck(:id)
    q = 8
    sl = (arr.size % q != 0) ? (arr.size / q + 1) : (arr.size / q)
    slice = arr.each_slice(sl).to_a
    slice.each do |ids|
      EmailWorker.perform_async(ids)
    end
  end

  def import
    if params[:file].present?
      imp = Customer.import(params[:file])
      if imp.empty?
        flash[:notice] = "Customers imported!"
        redirect_to customers_path
      else
        flash[:error] = imp
        redirect_to customers_path
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :status)
    end
end

app/controllers/email_templates_controller.rb
class EmailTemplatesController < ApplicationController
  before_action :set_email_template, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token  

  # GET /email_templates
  # GET /email_templates.json
  def index
    @email_templates = EmailTemplate.all.order(updated_at: :desc).page(params[:page]).per(10)
    @et = if params[:et].present?
      EmailTemplate.find(params[:et].to_i)
    else
      EmailTemplate.find(Setting.find_by_key('email_template').value.to_i)
    end
  end

  # GET /email_templates/1
  # GET /email_templates/1.json
  def show
  end

  # GET /email_templates/new
  def new
    @email_template = EmailTemplate.new
  end

  # GET /email_templates/1/edit
  def edit
  end

  # POST /email_templates
  # POST /email_templates.json
  def create
    @email_template = EmailTemplate.new(email_template_params)

    respond_to do |format|
      if @email_template.save
        format.html { redirect_to email_templates_path, notice: 'Email template was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /email_templates/1
  # PATCH/PUT /email_templates/1.json
  def update
    respond_to do |format|
      if @email_template.update(email_template_params)
        format.html { redirect_to email_templates_path, notice: 'Email template was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /email_templates/1
  # DELETE /email_templates/1.json
  def destroy
    @email_template.destroy
    respond_to do |format|
      format.html { redirect_to email_templates_url, notice: 'Email template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def choose_template
    email_tpl_setting = Setting.find_by_key("email_template")
    email_tpl_setting.value = params[:choose_template]
    email_tpl_setting.save!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email_template
      @email_template = EmailTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_template_params
      params.require(:email_template).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/email_templates_helper.rb
module EmailTemplatesHelper
end

app/views/customers/_form.html.erb
<%= form_for(customer, html: { class: "form-horizontal" }) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :status, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :status, class: "form-control", placeholder: "Status" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit 'Submit', :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<% if flash[:notice] %><p class="list-group-item list-group-item-success" id="notice"><%= flash[:notice] %></p><% end %>
<p id="error">
  <% if flash[:error] %>
    <ul class="list-group">
    <% flash[:error].each do |e| %>
      <li class="list-group-item list-group-item-danger"><%= e %></li>
    <% end %>
    </ul>
  <% end %>
</p>

<h1>Customers</h1>
<div class="col-sm-6">
  <%= link_to 'Email to all customers', "#", class: "btn btn-success all-email", data: { confirm: 'Are you sure?' } %>
  <%= text_field_tag 'min', nil, class: "form-control", style: "display: inline-block; width: 70px;", placeholder: "Offset" %>
  <%= text_field_tag 'max', nil, class: "form-control", style: "display: inline-block; width: 70px;", placeholder: "Limit" %>
  <%= link_to 'Multi Email', "#", class: "btn btn-success multi-email", data: { confirm: 'Are you sure?' } %>
</div>
<div class="col-sm-6">
  <%= form_tag '/customers/import', multipart: true, style: "float: right;" do %>
    <%= submit_tag 'Import', class: "btn btn-warning" %>
    <%= file_field_tag 'file', style: "display: inline-block;" %>
  <% end %>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.status %></td>
        <td><%= link_to 'Email', "#", class: "btn btn-success single-email", "data-id": customer.id %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', customer, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @customers %>
<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Status:</strong>
  <%= @customer.status %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/email_templates/_form.html.erb
<%= form_for(email_template, html: { class: "form-horizontal" }) do |f| %>
  <% if email_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(email_template.errors.count, "error") %> prohibited this email_template from being saved:</h2>

      <ul>
      <% email_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "control-label col-sm-2" %>
    <div class="col-sm-10">
      <%= f.text_area :content, class: "form-control", rows: 10 %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit 'Submit', :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/email_templates/edit.html.erb
<h1>Editing Email Template</h1>

<%= render 'form', email_template: @email_template %>

<%= link_to 'Back', email_templates_path %>

app/views/email_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Email Templates</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Preview</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @email_templates.each do |email_template| %>
      <% pr_checked = false %>
      <% pr_checked = true if email_template.id == @et.id %>
      <tr>
        <td><%= radio_button_tag("preview[]", "#{email_template.id}", pr_checked, onclick: "javascript:location.href='?et=#{email_template.id}'") %></td>
        <td><%= email_template.title %></td>
        <td><%= link_to 'Edit', edit_email_template_path(email_template), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', email_template, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @email_templates %>
<br>

<%= link_to 'New Email Template', new_email_template_path %>

<div class="container template-preview text-center">
<div class="row">
  <%= raw @et.content %>
</div>
<div class="row" style="margin-top: 20px; margin-bottom: 20px;">
  <form action="/email_templates/choose_template" method="post">
    <input type="hidden" name="choose_template" value="<%= @et.id %>">
    <input type="submit" value="Save" class="btn btn-warning">
  </form>
</div>
</div>

app/views/email_templates/new.html.erb
<h1>New Email Template</h1>

<%= render 'form', email_template: @email_template %>

<%= link_to 'Back', email_templates_path %>

app/views/email_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @email_template.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @email_template.content %>
</p>

<%= link_to 'Edit', edit_email_template_path(@email_template) %> |
<%= link_to 'Back', email_templates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmailBatcher</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>
  </head>

  <body>
  	<nav class="navbar navbar-inverse">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="<%= customers_path %>">Email Batcher</a>
		    </div>
		    <ul class="nav navbar-nav">
		      <li class=""><a href="<%= customers_path %>">Home</a></li>
		      <li class=""><a href="<%= email_templates_path %>">Email Templates</a></li>
		    </ul>
		    <form class="navbar-form navbar-left">
		      <div class="form-group">
		        <input type="text" class="form-control" placeholder="Search">
		      </div>
		      <button type="submit" class="btn btn-default">Search</button>
		    </form>
		  </div>
		</nav>
    <div class="container">
    	<%= yield %>
    </div>
  </body>
</html>